In [ ]:
import torch
from IPython.display import display

In [ ]:
torch.__version__

'1.11.0'

# Tensor

Tensors are the equivalent of `numpy`'s `ndarray`, and they can be computed on
GPU

## Tensor Creation

In [ ]:
torch.zeros((4, 10), dtype=torch.float32)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
torch.empty((4, 10), dtype=torch.float32)

tensor([[ 0.0000e+00,  2.0000e+00,  3.5282e-28, -8.5899e+09,  2.2408e-38,
          1.4013e-45,  4.6165e-35,  1.4013e-45,  3.7864e-37,  1.4013e-45],
        [ 2.1693e-38,  1.4013e-45,  4.6165e-35,  1.4013e-45,  4.6189e-35,
          1.4013e-45,  4.6165e-35,  1.4013e-45,  1.4303e-35,  1.4013e-45],
        [ 2.1628e-38,  1.4013e-45,  2.1628e-38,  1.4013e-45,  2.2473e-38,
          1.4013e-45,  5.3716e-37,  1.4013e-45,  2.2120e-38,  1.4013e-45],
        [ 2.2473e-38,  1.4013e-45,  9.0827e-36,  1.4013e-45,  4.6378e-35,
          1.4013e-45,  0.0000e+00,  2.0000e+00,  3.5309e-28, -1.5846e+29]])

In [ ]:
torch.rand((4, 10), dtype=torch.float32)

tensor([[0.2564, 0.9481, 0.8120, 0.9885, 0.3231, 0.6685, 0.7004, 0.5146, 0.1550,
         0.2769],
        [0.3161, 0.6031, 0.0431, 0.1045, 0.6932, 0.3589, 0.6445, 0.8288, 0.2985,
         0.2794],
        [0.3981, 0.2658, 0.4455, 0.6055, 0.4620, 0.4516, 0.5784, 0.9987, 0.0493,
         0.9786],
        [0.7288, 0.6941, 0.4363, 0.1375, 0.1822, 0.1354, 0.1759, 0.7272, 0.4636,
         0.9475]])

In [ ]:
torch.tensor([1, 2, 3])

tensor([1, 2, 3])

## Tensor Shape

### View

In [ ]:
torch \
    .zeros((4, 10), dtype=torch.float32) \
    .view(torch.int16)


tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=torch.int16)

In [ ]:
torch \
    .zeros((4, 10), dtype=torch.float32) \
    .view((40,))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

View share the same underlying data with a tensor. Therefore, **changing the 
tensor changes its view**

In [ ]:
def view_change_data():
    x_copy = torch.zeros((4, 10)).clone()
    x_copy_view = x_copy.view((40,))
    x_copy[0] = 100

    display(x_copy_view)


view_change_data()

tensor([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.])

### Reshape

In [ ]:
torch \
    .zeros((4, 10), dtype=torch.float32) \
    .reshape((40,))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**Reshaped tensor does not always return a copy**.

In [ ]:
def reshape_change_data():
    x_copy = torch.zeros((4, 10)).clone()
    x_copy_view = x_copy.reshape((40,))
    x_copy[0] = 100

    display(x_copy_view)


reshape_change_data()

tensor([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.])

## Operations

In [ ]:
def operation_using_operator():
    x = torch.tensor([1, 2, 3])
    x = x ** 2

    display(x)


operation_using_operator()

tensor([1, 4, 9])

In [ ]:
def operation_using_function():
    x = torch.tensor([1, 2, 3])
    x = torch.pow(x, 2)

    display(x)


operation_using_function()

tensor([1, 4, 9])

### In Place Mutation

In place modifiers are named as `operation_`

In [ ]:
def in_place_mutation():
    x = torch.zeros((10,)) 
    x.fill_(10)

    display(x)


in_place_mutation()

tensor([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])